FROM dockerproxy.cn/eclipse-temurin:21 AS jre-build

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime
# Define your base image
FROM dockerproxy.cn/debian:buster-slim
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /javaruntime $JAVA_HOME

WORKDIR /
COPY HelloWorld.class /
ENTRYPOINT java --enable-preview -XshowSettings:system -Xlog:gc=info HelloWorld
