global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "scrm-api"
    metrics_path: /scrm-api/actuator/prometheus
    static_configs:
      - targets: ["scrm-api:9080"]
  - job_name: "admin-server"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["admin-server:8080"]
  - job_name: "chat-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["chat-app:9081"]
